//
// Generated file, do not edit! Created by nedtool 4.6 from Messages/SIMCAN_App_IO_Message.msg.
//

#ifndef _SIMCAN_APP_IO_MESSAGE_M_H_
#define _SIMCAN_APP_IO_MESSAGE_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
	#include "SIMCAN_Message.h"
			
// }}

/**
 * Class generated from <tt>Messages/SIMCAN_App_IO_Message.msg:15</tt> by nedtool.
 * <pre>
 * ///
 * /// SIMCAN Message for IO requests
 * ///
 * message SIMCAN_App_IO_Message extends SIMCAN_Message
 * {
 *     @customize(true);
 * 
 *     string fileName = "";		// File name
 *     unsigned int offset = 0;	// Offset		
 *     unsigned int size = 0;		// Request size
 *     bool isPending = false;		// Is current request pending?			
 * }
 * </pre>
 *
 * SIMCAN_App_IO_Message_Base is only useful if it gets subclassed, and SIMCAN_App_IO_Message is derived from it.
 * The minimum code to be written for SIMCAN_App_IO_Message is the following:
 *
 * <pre>
 * class SIMCAN_App_IO_Message : public SIMCAN_App_IO_Message_Base
 * {
 *   private:
 *     void copy(const SIMCAN_App_IO_Message& other) { ... }

 *   public:
 *     SIMCAN_App_IO_Message(const char *name=NULL, int kind=0) : SIMCAN_App_IO_Message_Base(name,kind) {}
 *     SIMCAN_App_IO_Message(const SIMCAN_App_IO_Message& other) : SIMCAN_App_IO_Message_Base(other) {copy(other);}
 *     SIMCAN_App_IO_Message& operator=(const SIMCAN_App_IO_Message& other) {if (this==&other) return *this; SIMCAN_App_IO_Message_Base::operator=(other); copy(other); return *this;}
 *     virtual SIMCAN_App_IO_Message *dup() const {return new SIMCAN_App_IO_Message(*this);}
 *     // ADD CODE HERE to redefine and implement pure virtual functions from SIMCAN_App_IO_Message_Base
 * };
 * </pre>
 *
 * The following should go into a .cc (.cpp) file:
 *
 * <pre>
 * Register_Class(SIMCAN_App_IO_Message);
 * </pre>
 */
class SIMCAN_App_IO_Message_Base : public ::SIMCAN_Message
{
  protected:
    opp_string fileName_var;
    unsigned int offset_var;
    unsigned int size_var;
    bool isPending_var;

  private:
    void copy(const SIMCAN_App_IO_Message_Base& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const SIMCAN_App_IO_Message_Base&);
    // make constructors protected to avoid instantiation
    SIMCAN_App_IO_Message_Base(const char *name=NULL, int kind=0);
    SIMCAN_App_IO_Message_Base(const SIMCAN_App_IO_Message_Base& other);
    // make assignment operator protected to force the user override it
    SIMCAN_App_IO_Message_Base& operator=(const SIMCAN_App_IO_Message_Base& other);

  public:
    virtual ~SIMCAN_App_IO_Message_Base();
    virtual SIMCAN_App_IO_Message_Base *dup() const {throw cRuntimeError("You forgot to manually add a dup() function to class SIMCAN_App_IO_Message");}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getFileName() const;
    virtual void setFileName(const char * fileName);
    virtual unsigned int getOffset() const;
    virtual void setOffset(unsigned int offset);
    virtual unsigned int getSize() const;
    virtual void setSize(unsigned int size);
    virtual bool getIsPending() const;
    virtual void setIsPending(bool isPending);
};


#endif // ifndef _SIMCAN_APP_IO_MESSAGE_M_H_

