//
// Generated file, do not edit! Created by nedtool 4.6 from Messages/SIMCAN_MPI_Message.msg.
//

#ifndef _SIMCAN_MPI_MESSAGE_M_H_
#define _SIMCAN_MPI_MESSAGE_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
	#include "SIMCAN_App_NET_Message.h"
			
// }}

/**
 * Class generated from <tt>Messages/SIMCAN_MPI_Message.msg:15</tt> by nedtool.
 * <pre>
 * ///
 * /// SIMCAN Message for MPI calls
 * ///
 * message SIMCAN_MPI_Message extends SIMCAN_App_NET_Message
 * {
 *     @customize(true);
 * 
 *     unsigned int sourceRank = 0;	// Rank of the source process
 *     unsigned int destRank = 0;		// Rank of the destination process
 *     string fileName = "";			// File name
 *     int offset = 0;					// Offset			
 *     unsigned int sequence = 0;		// Sequence number	
 * }
 * </pre>
 *
 * SIMCAN_MPI_Message_Base is only useful if it gets subclassed, and SIMCAN_MPI_Message is derived from it.
 * The minimum code to be written for SIMCAN_MPI_Message is the following:
 *
 * <pre>
 * class SIMCAN_MPI_Message : public SIMCAN_MPI_Message_Base
 * {
 *   private:
 *     void copy(const SIMCAN_MPI_Message& other) { ... }

 *   public:
 *     SIMCAN_MPI_Message(const char *name=NULL, int kind=0) : SIMCAN_MPI_Message_Base(name,kind) {}
 *     SIMCAN_MPI_Message(const SIMCAN_MPI_Message& other) : SIMCAN_MPI_Message_Base(other) {copy(other);}
 *     SIMCAN_MPI_Message& operator=(const SIMCAN_MPI_Message& other) {if (this==&other) return *this; SIMCAN_MPI_Message_Base::operator=(other); copy(other); return *this;}
 *     virtual SIMCAN_MPI_Message *dup() const {return new SIMCAN_MPI_Message(*this);}
 *     // ADD CODE HERE to redefine and implement pure virtual functions from SIMCAN_MPI_Message_Base
 * };
 * </pre>
 *
 * The following should go into a .cc (.cpp) file:
 *
 * <pre>
 * Register_Class(SIMCAN_MPI_Message);
 * </pre>
 */
class SIMCAN_MPI_Message_Base : public ::SIMCAN_App_NET_Message
{
  protected:
    unsigned int sourceRank_var;
    unsigned int destRank_var;
    opp_string fileName_var;
    int offset_var;
    unsigned int sequence_var;

  private:
    void copy(const SIMCAN_MPI_Message_Base& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const SIMCAN_MPI_Message_Base&);
    // make constructors protected to avoid instantiation
    SIMCAN_MPI_Message_Base(const char *name=NULL, int kind=0);
    SIMCAN_MPI_Message_Base(const SIMCAN_MPI_Message_Base& other);
    // make assignment operator protected to force the user override it
    SIMCAN_MPI_Message_Base& operator=(const SIMCAN_MPI_Message_Base& other);

  public:
    virtual ~SIMCAN_MPI_Message_Base();
    virtual SIMCAN_MPI_Message_Base *dup() const {throw cRuntimeError("You forgot to manually add a dup() function to class SIMCAN_MPI_Message");}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned int getSourceRank() const;
    virtual void setSourceRank(unsigned int sourceRank);
    virtual unsigned int getDestRank() const;
    virtual void setDestRank(unsigned int destRank);
    virtual const char * getFileName() const;
    virtual void setFileName(const char * fileName);
    virtual int getOffset() const;
    virtual void setOffset(int offset);
    virtual unsigned int getSequence() const;
    virtual void setSequence(unsigned int sequence);
};


#endif // ifndef _SIMCAN_MPI_MESSAGE_M_H_

