//
// Generated file, do not edit! Created by nedtool 4.6 from Messages/SIMCAN_App_MEM_Message.msg.
//

#ifndef _SIMCAN_APP_MEM_MESSAGE_M_H_
#define _SIMCAN_APP_MEM_MESSAGE_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
	#include "SIMCAN_Message.h"
			
// }}

/**
 * Class generated from <tt>Messages/SIMCAN_App_MEM_Message.msg:15</tt> by nedtool.
 * <pre>
 * ///
 * /// SIMCAN Message for MEM requests
 * ///
 * message SIMCAN_App_MEM_Message extends SIMCAN_Message
 * {
 *     @customize(true);
 * 
 *     unsigned int memSize = 0;		// Amount of memory
 *     unsigned int region = 0;		// Region of memory
 * }
 * </pre>
 *
 * SIMCAN_App_MEM_Message_Base is only useful if it gets subclassed, and SIMCAN_App_MEM_Message is derived from it.
 * The minimum code to be written for SIMCAN_App_MEM_Message is the following:
 *
 * <pre>
 * class SIMCAN_App_MEM_Message : public SIMCAN_App_MEM_Message_Base
 * {
 *   private:
 *     void copy(const SIMCAN_App_MEM_Message& other) { ... }

 *   public:
 *     SIMCAN_App_MEM_Message(const char *name=NULL, int kind=0) : SIMCAN_App_MEM_Message_Base(name,kind) {}
 *     SIMCAN_App_MEM_Message(const SIMCAN_App_MEM_Message& other) : SIMCAN_App_MEM_Message_Base(other) {copy(other);}
 *     SIMCAN_App_MEM_Message& operator=(const SIMCAN_App_MEM_Message& other) {if (this==&other) return *this; SIMCAN_App_MEM_Message_Base::operator=(other); copy(other); return *this;}
 *     virtual SIMCAN_App_MEM_Message *dup() const {return new SIMCAN_App_MEM_Message(*this);}
 *     // ADD CODE HERE to redefine and implement pure virtual functions from SIMCAN_App_MEM_Message_Base
 * };
 * </pre>
 *
 * The following should go into a .cc (.cpp) file:
 *
 * <pre>
 * Register_Class(SIMCAN_App_MEM_Message);
 * </pre>
 */
class SIMCAN_App_MEM_Message_Base : public ::SIMCAN_Message
{
  protected:
    unsigned int memSize_var;
    unsigned int region_var;

  private:
    void copy(const SIMCAN_App_MEM_Message_Base& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const SIMCAN_App_MEM_Message_Base&);
    // make constructors protected to avoid instantiation
    SIMCAN_App_MEM_Message_Base(const char *name=NULL, int kind=0);
    SIMCAN_App_MEM_Message_Base(const SIMCAN_App_MEM_Message_Base& other);
    // make assignment operator protected to force the user override it
    SIMCAN_App_MEM_Message_Base& operator=(const SIMCAN_App_MEM_Message_Base& other);

  public:
    virtual ~SIMCAN_App_MEM_Message_Base();
    virtual SIMCAN_App_MEM_Message_Base *dup() const {throw cRuntimeError("You forgot to manually add a dup() function to class SIMCAN_App_MEM_Message");}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned int getMemSize() const;
    virtual void setMemSize(unsigned int memSize);
    virtual unsigned int getRegion() const;
    virtual void setRegion(unsigned int region);
};


#endif // ifndef _SIMCAN_APP_MEM_MESSAGE_M_H_

